"""crear tablas de capturas

Revision ID: 2028717654be
Revises: 
Create Date: 2026-09-28 09:05:20.080493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2028717654be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capturado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tag_clan', sa.String(length=20), nullable=False),
    sa.Column('nombre_clan', sa.String(length=50), nullable=False),
    sa.Column('nivel_clan', sa.Integer(), nullable=False),
    sa.Column('total_miembros', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capturas_miembros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captura_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('nivel_experiencia', sa.Integer(), nullable=False),
    sa.Column('nivel_ayuntamiento', sa.Integer(), nullable=False),
    sa.Column('trofeos', sa.Integer(), nullable=False),
    sa.Column('donaciones', sa.Integer(), nullable=False),
    sa.Column('donaciones_recibidas', sa.Integer(), nullable=False),
    sa.Column('liga', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['captura_id'], ['capturas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('captura_id', 'tag')
    )
    op.create_index(op.f('ix_capturas_miembros_captura_id'), 'capturas_miembros', ['captura_id'], unique=False)
    op.create_index(op.f('ix_capturas_miembros_tag'), 'capturas_miembros', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capturas_miembros_tag'), table_name='capturas_miembros')
    op.drop_index(op.f('ix_capturas_miembros_captura_id'), table_name='capturas_miembros')
    op.drop_table('capturas_miembros')
    op.drop_table('capturas')
    # ### end Alembic commands ###
