"""agregar tablas de asaltos a la capital del clan

Revision ID: 4b9336b32128
Revises: 8a59caa4d467
Create Date: 2026-09-30 13:39:23.628359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9336b32128'
down_revision: Union[str, Sequence[str], None] = '8a59caa4d467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asaltos_capital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('oro_capital_total', sa.Integer(), nullable=False),
    sa.Column('asaltos_completados', sa.Integer(), nullable=False),
    sa.Column('ataques_totales', sa.Integer(), nullable=False),
    sa.Column('distritos_rivales_destruidos', sa.Integer(), nullable=False),
    sa.Column('recompensa_ofensiva', sa.Integer(), nullable=False),
    sa.Column('recompensa_defensiva', sa.Integer(), nullable=False),
    sa.Column('primera_captura_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultima_actualizacion_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inicio')
    )
    op.create_table('asalto_miembros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asalto_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('ataques_usados', sa.Integer(), nullable=False),
    sa.Column('limite_ataques', sa.Integer(), nullable=False),
    sa.Column('ataques_bono', sa.Integer(), nullable=False),
    sa.Column('oro_capital_saqueado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asalto_id'], ['asaltos_capital.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asalto_id', 'tag')
    )
    op.create_index(op.f('ix_asalto_miembros_asalto_id'), 'asalto_miembros', ['asalto_id'], unique=False)
    op.create_index(op.f('ix_asalto_miembros_tag'), 'asalto_miembros', ['tag'], unique=False)
    op.create_table('asalto_registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asalto_id', sa.Integer(), nullable=False),
    sa.Column('sentido', sa.String(length=10), nullable=False),
    sa.Column('clan_tag', sa.String(length=20), nullable=False),
    sa.Column('clan_nombre', sa.String(length=50), nullable=False),
    sa.Column('clan_nivel', sa.Integer(), nullable=False),
    sa.Column('ataques_usados', sa.Integer(), nullable=False),
    sa.Column('distritos_totales', sa.Integer(), nullable=False),
    sa.Column('distritos_destruidos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asalto_id'], ['asaltos_capital.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asalto_registros_asalto_id'), 'asalto_registros', ['asalto_id'], unique=False)
    op.create_table('asalto_distritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('distrito_id_juego', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('destruccion', sa.Integer(), nullable=False),
    sa.Column('estrellas', sa.Integer(), nullable=False),
    sa.Column('ataques_usados', sa.Integer(), nullable=False),
    sa.Column('saqueado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['registro_id'], ['asalto_registros.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asalto_distritos_registro_id'), 'asalto_distritos', ['registro_id'], unique=False)
    op.create_table('asalto_ataques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distrito_id', sa.Integer(), nullable=False),
    sa.Column('atacante_tag', sa.String(length=20), nullable=False),
    sa.Column('atacante_nombre', sa.String(length=50), nullable=False),
    sa.Column('estrellas', sa.Integer(), nullable=False),
    sa.Column('destruccion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['distrito_id'], ['asalto_distritos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asalto_ataques_atacante_tag'), 'asalto_ataques', ['atacante_tag'], unique=False)
    op.create_index(op.f('ix_asalto_ataques_distrito_id'), 'asalto_ataques', ['distrito_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asalto_ataques_distrito_id'), table_name='asalto_ataques')
    op.drop_index(op.f('ix_asalto_ataques_atacante_tag'), table_name='asalto_ataques')
    op.drop_table('asalto_ataques')
    op.drop_index(op.f('ix_asalto_distritos_registro_id'), table_name='asalto_distritos')
    op.drop_table('asalto_distritos')
    op.drop_index(op.f('ix_asalto_registros_asalto_id'), table_name='asalto_registros')
    op.drop_table('asalto_registros')
    op.drop_index(op.f('ix_asalto_miembros_tag'), table_name='asalto_miembros')
    op.drop_index(op.f('ix_asalto_miembros_asalto_id'), table_name='asalto_miembros')
    op.drop_table('asalto_miembros')
    op.drop_table('asaltos_capital')
    # ### end Alembic commands ###
