"""agregar columnas de liga de guerras a guerras

Revision ID: 8a59caa4d467
Revises: ccc88d67134c
Create Date: 2026-09-29 22:04:50.424689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a59caa4d467'
down_revision: Union[str, Sequence[str], None] = 'ccc88d67134c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guerras', sa.Column('war_tag', sa.String(length=20), nullable=True))
    op.add_column('guerras', sa.Column('liga_temporada', sa.String(length=10), nullable=True))
    op.add_column('guerras', sa.Column('liga_ronda', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'guerras', ['war_tag'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'guerras', type_='unique')
    op.drop_column('guerras', 'liga_ronda')
    op.drop_column('guerras', 'liga_temporada')
    op.drop_column('guerras', 'war_tag')
    # ### end Alembic commands ###
