"""agregar rango y aldea de constructor a miembros

Revision ID: 9edac4aad473
Revises: 2028717654be
Create Date: 2026-09-28 19:41:31.768999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9edac4aad473'
down_revision: Union[str, Sequence[str], None] = '2028717654be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capturas_miembros', sa.Column('rango_clan', sa.Integer(), nullable=True))
    op.add_column('capturas_miembros', sa.Column('rango_clan_anterior', sa.Integer(), nullable=True))
    op.add_column('capturas_miembros', sa.Column('trofeos_base', sa.Integer(), nullable=True))
    op.add_column('capturas_miembros', sa.Column('liga_base', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capturas_miembros', 'liga_base')
    op.drop_column('capturas_miembros', 'trofeos_base')
    op.drop_column('capturas_miembros', 'rango_clan_anterior')
    op.drop_column('capturas_miembros', 'rango_clan')
    # ### end Alembic commands ###
