"""agregar tablas de guerras

Revision ID: ccc88d67134c
Revises: 9edac4aad473
Create Date: 2026-09-29 01:40:56.488423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc88d67134c'
down_revision: Union[str, Sequence[str], None] = '9edac4aad473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guerras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('tamano_equipo', sa.Integer(), nullable=True),
    sa.Column('ataques_por_miembro', sa.Integer(), nullable=True),
    sa.Column('modificador_batalla', sa.String(length=20), nullable=True),
    sa.Column('preparacion_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clan_tag', sa.String(length=20), nullable=False),
    sa.Column('clan_nombre', sa.String(length=50), nullable=False),
    sa.Column('clan_nivel', sa.Integer(), nullable=False),
    sa.Column('clan_estrellas', sa.Integer(), nullable=False),
    sa.Column('clan_destruccion', sa.Float(), nullable=False),
    sa.Column('clan_ataques_usados', sa.Integer(), nullable=True),
    sa.Column('clan_experiencia_ganada', sa.Integer(), nullable=True),
    sa.Column('rival_tag', sa.String(length=20), nullable=False),
    sa.Column('rival_nombre', sa.String(length=50), nullable=False),
    sa.Column('rival_nivel', sa.Integer(), nullable=False),
    sa.Column('rival_estrellas', sa.Integer(), nullable=False),
    sa.Column('rival_destruccion', sa.Float(), nullable=False),
    sa.Column('primera_captura_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultima_actualizacion_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('preparacion_inicio')
    )
    op.create_table('guerra_ataques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guerra_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('atacante_tag', sa.String(length=20), nullable=False),
    sa.Column('atacante_nombre', sa.String(length=50), nullable=False),
    sa.Column('defensor_tag', sa.String(length=20), nullable=False),
    sa.Column('defensor_nombre', sa.String(length=50), nullable=False),
    sa.Column('estrellas', sa.Integer(), nullable=False),
    sa.Column('destruccion', sa.Float(), nullable=False),
    sa.Column('duracion_segundos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guerra_id'], ['guerras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guerra_id', 'atacante_tag', 'orden')
    )
    op.create_index(op.f('ix_guerra_ataques_atacante_tag'), 'guerra_ataques', ['atacante_tag'], unique=False)
    op.create_index(op.f('ix_guerra_ataques_defensor_tag'), 'guerra_ataques', ['defensor_tag'], unique=False)
    op.create_index(op.f('ix_guerra_ataques_guerra_id'), 'guerra_ataques', ['guerra_id'], unique=False)
    op.create_table('guerra_miembros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guerra_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('nivel_ayuntamiento', sa.Integer(), nullable=False),
    sa.Column('posicion_mapa', sa.Integer(), nullable=False),
    sa.Column('es_propio', sa.Boolean(), nullable=False),
    sa.Column('ataques_recibidos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guerra_id'], ['guerras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guerra_id', 'tag')
    )
    op.create_index(op.f('ix_guerra_miembros_guerra_id'), 'guerra_miembros', ['guerra_id'], unique=False)
    op.create_index(op.f('ix_guerra_miembros_tag'), 'guerra_miembros', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guerra_miembros_tag'), table_name='guerra_miembros')
    op.drop_index(op.f('ix_guerra_miembros_guerra_id'), table_name='guerra_miembros')
    op.drop_table('guerra_miembros')
    op.drop_index(op.f('ix_guerra_ataques_guerra_id'), table_name='guerra_ataques')
    op.drop_index(op.f('ix_guerra_ataques_defensor_tag'), table_name='guerra_ataques')
    op.drop_index(op.f('ix_guerra_ataques_atacante_tag'), table_name='guerra_ataques')
    op.drop_table('guerra_ataques')
    op.drop_table('guerras')
    # ### end Alembic commands ###
